services:
  redis:
    image: redis:6-alpine
    networks:
      - default
    ports:
      - 6379:6379
  bot:
    build: ./bot
    restart: always
    
    depends_on:
      - db
      - redis
    command: [ "python", "main.py"]
    volumes:
      - ./bot:/usr/src/app
  currencies:
    build: ./exchangers
    restart: always
    depends_on:
      - db
      - redis
      - bot
    command: [ "python", "currencies_main.py"]
    volumes:
      - ./exchangers:/usr/src/app
  transactions:
    build: ./exchangers
    restart: always
    depends_on:
      - db
      - redis
      - bot
    command: [ "python", "transactions_main.py"]
    volumes:
      - ./exchangers:/usr/src/app
  celery:
    build: ./celery
    restart: always
    depends_on:
      - db
      - redis
    command: ["celery", "--app=celery", "worker", "-l", "INFO"]
    volumes:
      - ./celery:/usr/src/app
  celery_beat:
    build: ./celery
    restart: always
    depends_on:
      - db
      - redis
    command: ["celery", "--app=celery", "beat", "-l", "INFO"]
    volumes:
      - ./celery:/usr/src/app
  db:
    container_name: "db"
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=general
    ports:
      - "5400:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_static
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html:ro
    restart: always
