services:
  redis:
    image: redis:6-alpine
    networks:
      - default
    ports:
      - 6379:6379

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
      - redis
    command: ["python", "main.py"]
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app

  auth:
    build: ./auth
    restart: always
    depends_on:
      - db
      - redis
    command: ["python", "main.py"]
    ports:
      - 8002:8002
    volumes:
      - ./auth:/usr/src/app

  admin:
    build: ./admin
    restart: always
    depends_on:
      - db
      - redis
    command: ["python", "main.py"]
    ports:
      - 8001:8001
    volumes:
      - ./admin:/usr/src/app

  currencies:
    build: ./exchangers
    restart: always
    depends_on:
      - db
      - redis
    command: [ "python", "currencies_main.py"]
    volumes:
      - ./exchangers:/usr/src/app

  transactions:
    build: ./exchangers
    restart: always
    depends_on:
      - db
      - redis
    command: [ "python", "transactions_main.py"]
    volumes:
      - ./exchangers:/usr/src/app

  db:
    container_name: "db"
    image:  pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=general
    ports:
      - "5400:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
