currency_name = {
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "XRP": "XRP",
    "USDT": "Tether",
    "SOL": "Solana",
    "BNB": "BNB",
    "USDC": "USDC",
    "DOGE": "Dogecoin",
    "ADA": "Cardano",
    "TRX": "TRON",
    "LINK": "Chainlink",
    "AVAX": "Avalanche",
    "SUI": "Sui",
    "XLM": "Stellar",
    "HBAR": "Hedera",
    "TON": "Toncoin",
    "SHIB": "Shiba Inu",
    "LTC": "Litecoin",
    "DOT": "Polkadot",
    "LEO": "UNUS SED LEO",
    "HYPE": "Hyperliquid",
    "BCH": "Bitcoin Cash",
    "BGB": "Bitget Token",
    "UNI": "Uniswap",
    "USDe": "Ethena USDe",
    "PEPE": "Pepe",
    "TRUMP": "OFFICIAL TRUMP",
    "NEAR": "NEAR Protocol",
    "DAI": "Dai",
    "ONDO": "Ondo",
    "AAVE": "Aave",
    "OM": "MANTRA",
    "APT": "Aptos",
    "ICP": "Internet Computer",
    "XMR": "Monero",
    "ETC": "Ethereum Classic",
    "MNT": "Mantle",
    "TAO": "Bittensor",
    "VET": "VeChain",
    "POL": "POL (ex-MATIC)",
    "CRO": "Cronos",
    "OKB": "OKB",
    "KAS": "Kaspa",
    "ALGO": "Algorand",
    "RENDER": "Render",
    "FIL": "Filecoin",
    "ARB": "Arbitrum",
    "FET": "Artificial Superintelligence Alliance",
    "ATOM": "Cosmos",
    "ENA": "Ethena",
    "RAY": "Raydium",
    "GT": "GateToken",
    "TIA": "Celestia",
    "OP": "Optimism",
    "THETA": "Theta Network",
    "STX": "Stacks",
    "IMX": "Immutable",
    "MOVE": "Movement",
    "BONK": "Bonk",
    "INJ": "Injective",
    "JUP": "Jupiter",
    "FDUSD": "First Digital USD",
    "WLD": "Worldcoin",
    "LDO": "Lido DAO",
    "KCS": "KuCoin Token",
    "GRT": "The Graph",
    "XDC": "XDC Network",
    "S": "Sonic (prev. FTM)",
    "FLR": "Flare",
    "DEXE": "DeXe",
    "SEI": "Sei",
    "VIRTUAL": "Virtuals Protocol",
    "JASMY": "JasmyCoin",
    "SAND": "The Sandbox",
    "QNT": "Quant",
    "WIF": "dogwifhat",
    "FLOKI": "FLOKI",
    "XCN": "Onyxcoin",
    "EOS": "EOS",
    "SPX": "SPX6900",
    "ENS": "Ethereum Name Service",
    "KAIA": "Kaia",
    "XTZ": "Tezos",
    "GALA": "Gala",
    "FARTCOIN": "Fartcoin",
    "IOTA": "IOTA",
    "PYTH": "Pyth Network",
    "MKR": "Maker",
    "FLOW": "Flow",
    "BTT": "BitTorrent [New]",
    "BSV": "Bitcoin SV",
    "CRV": "Curve DAO Token",
    "JTO": "Jito",
    "PENGU": "Pudgy Penguins",
    "NEO": "Neo",
    "RON": "Ronin",
    "NEXO": "Nexo",
    "AR": "Arweave",
    "MANA": "Decentraland",
    "AXS": "Axie Infinity",
    "AIOZ": "AIOZ Network",
    "STRK": "Starknet",
    "AERO": "Aerodrome Finance",
    "EGLD": "MultiversX",
    "BRETT": "Brett (Based)",
    "DEEP": "DeepBook Protocol",
    "BEAM": "Beam",
    "MATIC": "Polygon",
    "RUNE": "THORChain",
    "DYDX": "dYdX (Native)",
    "HNT": "Helium",
    "CFX": "Conflux",
    "AI16Z": "ai16z",
    "USDD": "USDD",
    "ZEC": "Zcash",
    "MORPHO": "Morpho",
    "APE": "ApeCoin",
    "RSR": "Reserve Rights",
    "FTT": "FTX Token",
    "XAUt": "Tether Gold",
    "CORE": "Core",
    "EIGEN": "EigenLayer",
    "W": "Wormhole",
    "AKT": "Akash Network",
    "CHZ": "Chiliz",
    "XEC": "eCash",
    "COMP": "Compound",
    "AMP": "Amp",
    "CAKE": "PancakeSwap",
    "GIGA": "Gigachad (gigachadsolana.com)",
    "PENDLE": "Pendle",
    "MINA": "Mina",
    "PAXG": "PAX Gold",
    "GNO": "Gnosis",
    "SNX": "Synthetix",
    "ZK": "ZKsync",
    "PYUSD": "PayPal USD",
    "AXL": "Axelar",
    "SUPER": "SuperVerse",
    "TUSD": "TrueUSD",
    "TOSHI": "Toshi",
    "NFT": "APENFT",
    "KAVA": "Kava",
    "MOG": "Mog Coin",
    "NOT": "Notcoin",
    "ROSE": "Oasis",
    "1INCH": "1inch Network",
    "TWT": "Trust Wallet Token",
    "GRASS": "Grass",
    "SAFE": "Safe",
    "LUNC": "Terra Classic",
    "VTHO": "VeThor Token",
    "AIXBT": "aixbt by Virtuals",
    "LPT": "Livepeer",
    "KSM": "Kusama",
    "TFUEL": "Theta Fuel",
    "CTC": "Creditcoin",
    "DASH": "Dash",
    "ZRO": "LayerZero",
    "BLUR": "Blur",
    "MEW": "cat in a dogs world",
    "ORDI": "ORDI",
    "MELANIA": "Official Melania Meme",
    "CKB": "Nervos Network",
    "TURBO": "Turbo",
    "PRIME": "Echelon Prime",
    "ASTR": "Astar",
    "IO": "io.net",
    "JST": "JUST",
    "MX": "MX Token",
    "HOT": "Holo",
    "ZIL": "Zilliqa",
    "SKL": "SKALE",
    "ZRX": "0x Protocol",
    "ETHFI": "ether.fi",
    "ACH": "Alchemy Pay",
    "TRAC": "OriginTrail",
    "BabyDoge": "Baby Doge Coin",
    "MOCA": "Moca Network",
    "SFP": "SafePal",
    "POPCAT": "Popcat (SOL)",
    "ATH": "Aethir",
    "SUSHI": "SushiSwap",
    "BAT": "Basic Attention Token",
    "GLM": "Golem",
    "CVX": "Convex Finance",
    "BIO": "Bio Protocol",
    "ID": "SPACE ID",
    "WEMIX": "WEMIX",
    "ZEN": "Horizen",
    "GAS": "Gas",
    "CELO": "Celo",
    "WOO": "WOO",
    "QTUM": "Qtum",
    "IOTX": "IoTeX",
    "UXLINK": "UXLINK",
    "SC": "Siacoin",
    "XYO": "XYO",
    "OSMO": "Osmosis",
    "SPELL": "Spell Token",
    "FTN": "Fasttoken",
    "USD0": "Usual USD",
    "ZBU": "Zeebu",
    "SOS": "Solana Swap",
    "FLZ": "Fellaz",
    "SHIBTC": "ShibaBitcoin",
    "MGC": "Meta Games Coin",
    "FRAX": "Frax",
    "TEL": "Telcoin",
    "INSURANCE": "insurance",
    "ULTIMA": "Ultima",
    "BDX": "Beldex",
    "CHEX": "Chintai",
    "SNEK": "Snek",
    "CHEEL": "Cheelee",
    "NEW": "Newton",
    "MWC": "MimbleWimbleCoin",
    "ARC": "AI Rig Complex",
    "FAI": "Freysa",
    "USDY": "Ondo US Dollar Yield",
    "DOG": "Dog (Bitcoin)",
    "BORG": "SwissBorg",
    "TRIBE": "Tribe",
    "DSYNC": "Destra Network",
    "AIC": "AI Companions",
    "ONE": "Harmony",
    "ZETA": "ZetaChain",
    "ETHW": "EthereumPoW",
    "VANA": "Vana",
    "SATS": "SATS (Ordinals)",
    "ENJ": "Enjin Coin",
    "ANKR": "Ankr",
    "RVN": "Ravencoin",
    "MRS": "Metars Genesis",
    "DRIFT": "Drift",
    "MEME": "Memecoin",
    "VINE": "Vine Coin",
    "ELF": "aelf",
    "PNUT": "Peanut the Squirrel",
    "QUBIC": "Qubic",
    "GRIFFAIN": "GRIFFAIN",
    "ANIME": "Animecoin",
    "GMT": "GMT",
    "T": "Threshold",
    "ARKM": "Arkham",
    "ME": "Magic Eden",
    "DEUSD": "Elixir deUSD",
    "XCH": "Chia",
    "YFI": "yearn.finance",
    "BZR": "Bazaars",
    "BOME": "BOOK OF MEME",
    "AEVO": "Aevo",
    "PAAL": "PAAL AI",
    "MANTA": "Manta Network",
    "PEAQ": "peaq",
    "FXS": "Frax Share",
    "LRC": "Loopring",
    "KDA": "Kadena",
    "ETHDYDX": "dYdX (ethDYDX)",
    "LUNA": "Terra",
    "MASK": "Mask Network",
    "G": "Gravity",
    "BICO": "Biconomy",
    "MPLX": "Metaplex",
    "SSV": "ssv.network",
    "CPOOL": "Clearpool",
    "$AKUMA": "Akuma Inu",
    "NEIRO": "Neiro (First Neiro On Ethereum)",
    "ZKJ": "Polyhedra Network",
    "AVAIL": "Avail",
    "POLYX": "Polymesh",
    "HIVE": "Hive",
    "DYM": "Dymension",
    "USUAL": "Usual",
    "GMX": "GMX",
    "DCR": "Decred",
    "POLY": "Polymath",
    "XEM": "NEM",
    "METIS": "Metis",
    "GOMINING": "Go\u041cining",
    "TAI": "TARS AI",
    "VVV": "Venice Token",
    "SUN": "Sun [New]",
    "HONEY": "Hivemapper",
    "DESO": "Decentralized Social",
    "GOAT": "Goatseus Maximus",
    "DAG": "Constellation",
    "ONT": "Ontology",
    "FIDA": "Solana Name Service",
    "STIK": "Staika",
    "DGB": "DigiByte",
    "ALT": "Altlayer",
    "EDU": "Open Campus",
    "UMA": "UMA",
    "FLUX": "Flux",
    "WAVES": "Waves",
    "GPRO": "GoldPro Token",
    "LCX": "LCX",
    "SXP": "Solar",
    "CSPR": "Casper",
    "ACX": "Across Protocol",
    "RLB": "Rollbit Coin",
    "CGPT": "ChainGPT",
    "RPL": "Rocket Pool",
    "ACT": "Act I : The AI Prophecy",
    "SOLO": "Sologenic",
    "ANON": "Hey Anon",
    "HMSTR": "Hamster Kombat",
    "ORBR": "Orbler",
    "STORJ": "Storj",
    "XAI": "Xai",
    "ZIG": "ZIGChain",
    "COW": "CoW Protocol",
    "WAXP": "WAX",
    "AUDIO": "Audius",
    "JELLYJELLY": "Jelly-My-Jelly",
    "COTI": "COTI",
    "VELO": "Velo",
    "ILV": "Illuvium",
    "ICX": "ICON",
    "HEART": "Humans.ai",
    "KUB": "Bitkub Coin",
    "ACS": "Access Protocol",
    "SNT": "Status",
    "GLMR": "Moonbeam",
    "UPC": "UPCX",
    "VVS": "VVS Finance",
    "STPT": "STP",
    "XNO": "Nano",
    "PHA": "Phala Network",
    "POND": "Marlin",
    "WMTX": "World Mobile Token",
    "CHEEMS": "Cheems (cheems.pet)",
    "ORCA": "Orca",
    "WILD": "Wilder World",
    "XPR": "XPR Network",
    "UFD": "Unicorn Fart Dust",
    "BAL": "Balancer",
    "DOGS": "DOGS",
    "0x0": "0x0.ai",
    "LSK": "Lisk",
    "LQTY": "Liquity",
    "XVG": "Verge",
    "POWR": "Powerledger",
    "BIGTIME": "Big Time",
    "PEOPLE": "ConstitutionDAO",
    "ELON": "Dogelon Mars",
    "BLAST": "Blast",
    "TAIKO": "Taiko",
    "OZO": "Ozone Chain",
    "AGI": "Delysium",
    "HT": "Huobi Token",
    "CETUS": "Cetus Protocol",
    "SKI": "Ski Mask Dog",
    "BORA": "BORA",
    "CVC": "Civic",
    "ZENT": "Zentry",
    "YGG": "Yield Guild Games",
    "IQ": "IQ",
    "BITCOIN": "HarryPotterObamaSonic10Inu (ERC-20)",
    "CHR": "Chromia",
    "NPC": "Non-Playable Coin",
    "VANRY": "Vanar Chain",
    "PIXEL": "Pixels",
    "ABT": "Arcblock",
    "BB": "BounceBit",
    "BANANA": "Banana Gun",
    "PEPECOIN": "PepeCoin",
    "STRAX": "Stratis [New]",
    "DEVVE": "Devve",
    "EURS": "STASIS EURO",
    "SCR": "Scroll",
    "MVL": "MVL",
    "MYTH": "Mythos",
    "APU": "Apu Apustaja",
    "IOST": "IOST",
    "PEPU": "Pepe Unchained",
    "IAG": "IAGON",
    "TRB": "Tellor",
    "SAGA": "Saga",
    "XVS": "Venus",
    "RLC": "iExec RLC",
    "AI": "Sleepless AI",
    "WHITE": "WhiteRock",
    "CFG": "Centrifuge",
    "ONG": "Ontology Gas",
    "JOE": "JOE",
    "XRD": "Radix",
    "TRIBL": "Tribal Finance",
    "OMNI": "Omni Network",
    "SLP": "Smooth Love Potion",
    "AGLD": "Adventure Gold",
    "DKA": "dKargo",
    "JET": "Satoshi Airline",
    "AL": "ArchLoot",
    "ERG": "Ergo",
    "SHX": "Stronghold Token",
    "ANDY": "ANDY (ETH)",
    "CELR": "Celer Network",
    "C98": "Coin98",
    "KEEP": "Keep Network",
    "ZANO": "Zano",
    "CTSI": "Cartesi",
    "ALEO": "Aleo",
    "PUNDIX": "Pundi X (New)",
    "CARV": "CARV",
    "DENT": "Dent",
    "MOODENG": "Moo Deng (moodengsol.com)",
    "PYR": "Vulcan Forged (PYR)",
    "NOS": "Nosana",
    "FWOG": "Fwog (SOL)",
    "OXT": "Orchid",
    "CAT": "Simon's Cat",
    "SYRUP": "Maple Finance",
    "ORBS": "Orbs",
    "API3": "API3",
    "MIGGLES": "Mr Miggles",
    "NMT": "NetMind Token",
    "FUEL": "Fuel Network",
    "BTG": "Bitcoin Gold",
    "MLK": "MiL.k",
    "ALU": "Altura",
    "PRO": "Propy",
    "CUDOS": "CUDOS",
    "EURC": "EURC",
    "SDEX": "SmarDex",
    "OAS": "Oasys",
    "ASM": "Assemble AI",
    "STEEM": "Steem",
    "GME": "GameStop (gamestop-coin.vip)",
    "MAGIC": "Treasure",
    "COOKIE": "Cookie DAO",
    "METFI": "MetFi",
    "MED": "MediBloc",
    "NMR": "Numeraire",
    "KOGE": "48 Club Token",
    "LUMIA": "Lumia",
    "BMX": "BitMart Token",
    "AURORA": "Aurora",
    "ZEREBRO": "Zerebro",
    "GAME": "GameBuild",
    "SCRT": "Secret",
    "ARK": "Ark",
    "ORAI": "Oraichain",
    "WOLF": "Landwolf 0x67",
    "MTL": "Metal DAO",
    "BNX": "BinaryX",
    "LON": "Tokenlon Network Token",
    "ZRC": "Zircuit",
    "KNC": "Kyber Network Crystal v2",
    "REQ": "Request",
    "SFUND": "Seedify.fund",
    "PONKE": "Ponke",
    "PROM": "Prom",
    "DEGEN": "Degen",
    "SWFTC": "SwftCoin",
    "OMI": "ECOMI",
    "BASEDAI": "BasedAI",
    "WIN": "WINkLink",
    "PORTAL": "Portal",
    "SYN": "Synapse",
    "ALI": "Artificial Liquid Intelligence",
    "SEND": "Suilend",
    "MOVR": "Moonriver",
    "USDB": "USDB",
    "USDL": "Lift Dollar",
    "ACA": "Acala Token",
    "NTRN": "Neutron",
    "SURE": "inSure DeFi",
    "DF": "dForce",
    "ANYONE": "ANyONe Protocol",
    "APFC": "APF coin",
    "APEX": "ApeX Protocol",
    "SOLV": "Solv Protocol",
    "CTK": "Shentu",
    "VERUM": "Verum Coin",
    "ALPH": "Alephium",
    "USTC": "TerraClassicUSD",
    "HIGH": "Highstreet",
    "TRU": "TrueFi",
    "GPU": "Node AI",
    "BWB": "Bitget Wallet Token",
    "BTRST": "Braintrust",
    "ARDR": "Ardor",
    "XYM": "Symbol",
    "CYBER": "Cyber",
    "AUCTION": "Bounce Token",
    "BADGER": "Badger DAO",
    "PCI": "Paycoin",
    "AIAT": "AI Analysis Token",
    "CBK": "Cobak Token",
    "RIO": "Realio Network",
    "USDP": "Pax Dollar",
    "BONE": "Bone ShibaSwap",
    "RIF": "Rootstock Infrastructure Framework",
    "TOKAMAK": "Tokamak Network",
    "DUSK": "Dusk",
    "SLERF": "SLERF",
    "HFT": "Hashflow",
    "BNT": "Bancor",
    "D": "DAR Open Network",
    "HIFI": "Hifi Finance",
    "PHB": "Phoenix",
    "DODO": "DODO",
    "OLAS": "Autonolas",
    "AVA": "AVA",
    "GRIFT": "ORBIT",
    "NFP": "NFPrompt",
    "OSAK": "Osaka Protocol",
    "ZBCN": "Zebec Network",
    "HASHAI": "HashAI",
    "SYS": "Syscoin",
    "FX": "Pundi AI",
    "COREUM": "Coreum",
    "MERL": "Merlin Chain",
    "QKC": "QuarkChain",
    "CXT": "Covalent X Token",
    "CLV": "CLV",
    "PIPPIN": "pippin",
    "MODE": "Mode",
    "SAUCE": "SaucerSwap",
    "QI": "BENQI",
    "SWARMS": "Swarms",
    "lisUSD": "lisUSD",
    "RARE": "SuperRare",
    "NEURAL": "NeuralAI",
    "DPI": "DeFi Pulse Index",
    "TORN": "Tornado Cash",
    "MOBILE": "Helium Mobile",
    "USDTb": "Ethena Labs (USDTb)",
    "OX": "OX Coin",
    "SPEC": "Spectral",
    "NCT": "PolySwarm",
    "DIA": "DIA",
    "BUZZ": "Hive AI",
    "H2O": "H2O DAO",
    "GEOD": "GEODNET",
    "LOOM": "Loom Network",
    "STG": "Stargate Finance",
    "CATI": "Catizen",
    "NAKA": "Nakamoto Games",
    "DAO": "DAO Maker",
    "MBX": "MARBLEX",
    "STMX": "StormX",
    "LOFI": "LOFI",
    "AGRI": "AgriDex",
    "A8": "Ancient8",
    "HPO": "Hippocrat",
    "LMT": "Limitus",
    "WZRD": "Bitcoin Wizards",
    "ACE": "Fusionist",
    "RSS3": "RSS3",
    "HIPPO": "sudeng",
    "COQ": "Coq Inu",
    "OGN": "Origin Protocol",
    "AITECH": "Solidus Ai Tech",
    "MAV": "Maverick Protocol",
    "ALICE": "MyNeighborAlice",
    "USDX": "USDX [Kava]",
    "MYRIA": "Myria",
    "CET": "CoinEx Token",
    "RSC": "ResearchCoin",
    "TKO": "Toko Token",
    "XPLA": "XPLA",
    "ARPA": "ARPA",
    "X": "X Empire",
    "FORTH": "Ampleforth Governance Token",
    "NKN": "NKN",
    "CLUSTR": "Clustr Labs",
    "THE": "THENA",
    "SBD": "Steem Dollars",
    "GEAR": "Gearbox Protocol",
    "HOOK": "Hooked Protocol",
    "BUSD": "BUSD",
    "AZERO": "Aleph Zero",
    "MPL": "Maple",
    "vBUSD": "Venus BUSD",
    "PUFFER": "Puffer",
    "MBL": "MovieBloc",
    "EUL": "Euler",
    "LUSD": "Liquity USD",
    "BENJI": "Basenji",
    "PRQ": "PARSIQ",
    "MCDULL": "McDull",
    "CHILLGUY": "Just a chill guy",
    "LEVER": "LeverFi",
    "RETARDIO": "RETARDIO",
    "ATA": "Automata Network",
    "ALPHA": "Stella",
    "GUSD": "Gemini Dollar",
    "MBOX": "MOBOX",
    "LMWR": "LimeWire",
    "MIN": "Minswap",
    "YNE": "yesnoerror",
    "RACA": "RACA",
    "ICE": "Ice Open Network",
    "XMW": "Morphware",
    "M87": "MESSIER",
    "META": "Metadium",
    "GODS": "Gods Unchained",
    "WEN": "Wen",
    "F": "SynFutures",
    "MONKY": "Wise Monkey",
    "SUNDOG": "SUNDOG",
    "TNSR": "Tensor",
    "SHDW": "Shadow Token",
    "RDNT": "Radiant Capital",
    "PRCL": "Parcl",
    "AEUR": "Anchored Coins AEUR",
    "BAKE": "BakeryToken",
    "SHFL": "Shuffle",
    "BEL": "Bella Protocol",
    "BFC": "Bifrost",
    "TLM": "Alien Worlds",
    "VR": "Victoria VR",
    "TLOS": "Telos",
    "SWEAT": "Sweat Economy",
    "ANT": "Aragon",
    "RAD": "Radworks",
    "MAPO": "MAP Protocol",
    "ORA": "ORA",
    "UQC": "Uquid Coin",
    "CTXC": "Cortex",
    "ETN": "Electroneum",
    "PALM": "PaLM AI",
    "NYM": "NYM",
    "AERGO": "Aergo",
    "PNG": "Pangolin",
    "VCNT": "ViciCoin",
    "LYX": "LUKSO",
    "LAT": "PlatON",
    "REZ": "Renzo",
    "SHIRO": "Shiro Neko",
    "KUJI": "Kujira",
    "ORDER": "Orderly Network",
    "GTC": "Gitcoin",
    "AQT": "Alpha Quark Token",
    "UTK": "xMoney",
    "SD": "Stader",
    "ATR": "Artrade",
    "GNS": "Gains Network",
    "FORT": "Forta",
    "ISLM": "Islamic Coin",
    "ADS": "Alkimi",
    "LISTA": "Lista DAO",
    "DEP": "DEAPcoin",
    "MAJOR": "Major Frog",
    "$MICHI": "michi (SOL)",
    "REI": "REI Network",
    "STNK": "Stonks",
    "FCT": "FirmaChain",
    "RARI": "RARI",
    "SN": "SpaceN",
    "TAOBOT": "tao.bot",
    "HUNT": "Hunt Town",
    "PUPS": "Pups (Bitcoin)",
    "LADYS": "Milady Meme Coin",
    "MOCHI": "Mochi (New)",
    "MOC": "Moss Coin",
    "BGSC": "BugsCoin",
    "TT": "ThunderCore",
    "ELA": "Elastos",
    "ZCX": "Unizen",
    "RAI": "Reploy",
    "ERN": "Ethernity Chain",
    "CSWAP": "ChainSwap",
    "LTO": "LTO Network",
    "GRS": "Groestlcoin",
    "EURCV": "EUR CoinVertible",
    "ATLAS": "Star Atlas",
    "PERP": "Perpetual Protocol",
    "PXT": "Pixer Eternity",
    "OMG": "OMG Network",
    "LOCK": "Houdini Swap",
    "DBR": "deBridge",
    "DNT": "district0x",
    "MLN": "Enzyme",
    "MCT": "Metacraft",
    "ALCH": "Alchemist AI",
    "GHX": "GamerCoin",
    "GFI": "Goldfinch",
    "SWELL": "Swell Network",
    "XION": "XION",
    "DEGO": "Dego Finance",
    "NAVX": "NAVI Protocol",
    "GHST": "Aavegotchi",
    "ZEON": "ZEON",
    "SIGMA": "SIGMA",
    "BOUNTY": "Chainbounty",
    "MGP": "Magpie",
    "LIT": "Litentry",
    "EL": "ELYSIA",
    "BOBO": "BOBO",
    "BRISE": "Bitgert",
    "UOS": "Ultra",
    "FUN": "FUNToken",
    "GST": "Green Satoshi Token (SOL)",
    "IDEX": "IDEX",
    "NS": "Sui Name Service",
    "ALEX": "ALEX Lab",
    "$PURPE": "Purple Pepe",
    "MAX": "MAX",
    "EURt": "Tether EURt",
    "APX": "APX",
    "ALCX": "Alchemix",
    "POKT": "Pocket Network",
    "WOJAK": "Wojak",
    "KARRAT": "KARRAT",
    "NULS": "NULS",
    "XSGD": "XSGD",
    "BIM": "BIM",
    "ARRR": "Pirate Chain",
    "TOKEN": "TokenFi",
    "SPA": "Sperax",
    "VENOM": "Venom",
    "CCD": "Concordium",
    "CUSD": "Celo Dollar",
    "REKT": "Rekt (rektcoin.com)",
    "VADER": "VaderAI by Virtuals",
    "WAN": "Wanchain",
    "DATA": "Streamr",
    "SLND": "Solend",
    "DEXT": "DEXTools",
    "NGL": "Entangle",
    "USDG": "Global Dollar",
    "AMPL": "Ampleforth",
    "DADDY": "Daddy Tate",
    "POLS": "Polkastarter",
    "WUF": "WUFFI",
    "EWT": "Energy Web Token",
    "BAN": "Comedian",
    "AHT": "AhaToken",
    "FLM": "Flamingo",
    "TOKE": "Tokemak",
    "VRA": "Verasity",
    "GEMS": "Gems",
    "VIC": "Viction",
    "DIMO": "DIMO",
    "ELIZA": "Eliza (elizawakesup)",
    "IDIA": "Impossible Finance Launchpad",
    "BETA": "Beta Finance",
    "OCTA": "OctaSpace",
    "BOBA": "Boba Network",
    "HAI": "Hacken Token",
    "RAMP": "RAMP",
    "COS": "Contentos",
    "LOOKS": "LooksRare",
    "ODOS": "Odos",
    "SRX": "StorX Network",
    "AIDOGE": "ArbDoge AI",
    "GEL": "Gelato",
    "KMD": "Komodo",
    "GRND": "SuperWalk",
    "STRD": "Stride",
    "FIS": "StaFi",
    "POLIS": "Star Atlas DAO",
    "MDT": "Measurable Data Token",
    "OMIKAMI": "Amaterasu Omikami",
    "KIKI": "KIKICat",
    "MOB": "MobileCoin",
    "EURI": "Eurite",
    "ZKL": "zkLink",
    "VRTX": "Vertex Protocol",
    "QRL": "Quantum Resistant Ledger",
    "CROWN": "Crown by Third Time Games",
    "OGY": "ORIGYN",
    "OL": "Open Loot",
    "XPRT": "Persistence One",
    "STEP": "Step Finance",
    "HOSKY": "HOSKY Token",
    "QUACK": "RichQUACK.com",
    "CHESS": "Tranchess",
    "SIDUS": "SIDUS",
    "MYRO": "Myro",
    "PIKA": "Pikaboss",
    "MANEKI": "MANEKI",
    "AXOL": "Axol",
    "KISHU": "Kishu Inu",
    "BID": "CreatorBid",
    "VARA": "Vara Network",
    "ALEPH": "Aleph.im",
    "HOPPY": "Hoppy",
    "BSW": "Biswap",
    "NUM": "Numbers Protocol",
    "NPT": "NEOPIN",
    "LOKA": "League of Kingdoms Arena",
    "VOXEL": "Voxies",
    "BOSON": "Boson Protocol",
    "MASA": "Masa",
    "MCOIN": "MCOIN",
    "RSV": "Reserve Dollar",
    "ROOT": "The Root Network",
    "INV": "Inverse Finance",
    "OORT": "OORT",
    "NXRA": "Nexera",
    "WHY": "WHY",
    "RBN": "Ribbon Finance",
    "EVER": "Everscale",
    "LBT": "Law Blocks (AI)",
    "MNGO": "Mango",
    "OHO": "Oho",
    "BOTTO": "Botto",
    "eUSD": "Electronic USD",
    "DRGN": "Dragonchain",
    "QDX": "Quidax Token",
    "USDJ": "USDJ",
    "WXT": "Wirex Token",
    "DIONE": "Dione Protocol",
    "FARM": "Harvest Finance",
    "TPT": "TokenPocket",
    "TET": "Tectum",
    "CLANKER": "tokenbot",
    "MOZ": "Lumoz",
    "TARA": "Taraxa",
    "ZTX": "ZTX",
    "MATH": "MATH",
    "LOCUS": "Locus Chain",
    "XFI": "CrossFi",
    "SPECTRE": "SPECTRE AI",
    "KLV": "Klever Coin",
    "SUKU": "Suku",
    "GFAL": "Games for a Living",
    "KOMA": "Koma Inu",
    "LINA": "Linear Finance",
    "KEKIUS": "Kekius Maximus (kekiusmaximus.vip)",
    "MCADE": "Metacade",
    "KIN": "Kin",
    "CHAMP": "Super Champs",
    "REN": "Ren",
    "CONX": "Connex",
    "SNAI": "SwarmNode.ai",
    "BFG": "BFG Token",
    "ROG": "ROGin AI",
    "BDC": "BILLION\u2022DOLLAR\u2022CAT",
    "AGRS": "Agoras: Tau Net",
    "BLUE": "Bluefin",
    "BULLY": "Dolos The Bully",
    "AVINOC": "AVINOC",
    "FIO": "FIO Protocol",
    "AURA": "Aura Finance",
    "BKN": "Brickken",
    "CEEK": "CEEK VR",
    "GAFI": "GameFi.org",
    "BCA": "Bitcoin Atom",
    "QUICK": "QuickSwap [Old]",
    "SIX": "SIX",
    "KYVE": "KYVE Network",
    "AMO": "AMO Coin",
    "HEGIC": "Hegic",
    "BERT": "Bertram The Pomeranian",
    "HOPR": "HOPR",
    "ADX": "AdEx",
    "COMBO": "COMBO",
    "GROK": "Grok",
    "AIXCB": "aixCB by Virtuals",
    "STRX": "StrikeX",
    "PORK": "PepeFork",
    "HAT": "Top Hat",
    "PAID": "PAID",
    "FRIC": "Fric",
    "DORA": "Dora Factory",
    "HTR": "Hathor",
    "PROS": "Prosper",
    "VIDT": "VIDT DAO",
    "MMUI": "MetaMUI",
    "KASTA": "Kasta",
    "ISIKC": "Isiklar Coin",
    "PIRATE": "Pirate Nation",
    "PROPC": "Propchain",
    "ASD": "ASD",
    "SLF": "Self Chain",
    "FT": "FractonX",
    "AXEL": "AXEL",
    "GATSBY": "GATSBY (gatsby.fi)",
    "CAW": "crow with knife",
    "BIFI": "Beefy",
    "HYPC": "HyperCycle",
    "LEASH": "Doge Killer",
    "WING": "Wing Finance",
    "MIX": "MixMarvel",
    "FIRO": "Firo",
    "MLC": "My Lovely Planet",
    "SHPING": "SHPING",
    "QTCON": "Quiztok",
    "AKI": "Aki Network",
    "SANTOS": "Santos FC Fan Token",
    "SKEY": "Skey Network",
    "ZKML": "zKML",
    "SYNT": "Synternet",
    "MEMEFI": "MemeFi",
    "UFT": "UniLend",
    "AIMONICA": "Aimonica Brands",
    "MON": "MON",
    "FOXSY": "Foxsy AI",
    "CTX": "Cryptex Finance",
    "BLZ": "Bluzelle",
    "DMTR": "Dimitra",
    "COPI": "Cornucopias",
    "FLIX": "OmniFlix Network",
    "MAVIA": "Heroes of Mavia",
    "FOX": "Shapeshift FOX Token",
    "REX": "REVOX",
    "ASTRA": "AstraAI",
    "PIVX": "PIVX",
    "PDA": "PlayDapp",
    "PEIPEI": "PeiPei (ETH)",
    "BURGER": "BurgerCities",
    "OBT": "Oobit",
    "TRADE": "Polytrade",
    "GALEON": "Galeon",
    "ETF500": "Elon Trump Fart",
    "GOG": "Guild of Guardians",
    "SEN": "Sentio Protocol",
    "FOMO": "FOMO (fomo.fund)",
    "ALPACA": "Alpaca Finance",
    "OBSR": "Observer",
    "LAI": "LayerAI",
    "KENDU": "Kendu Inu",
    "PROPS": "Propbase",
    "OPUL": "Opulous",
    "AMB": "AirDAO",
    "XCP": "Counterparty",
    "DEAI": "Zero1 Labs",
    "GENE": "Genopets",
    "YAFA": "Free Palestine",
    "ZUSD": "ZUSD",
    "VXV": "Vectorspace AI",
    "TRISIG": "TRI SIGMA",
    "COL": "Clash of Lilliput",
    "PSG": "Paris Saint-Germain Fan Token",
    "SERAPH": "Seraph",
    "RBTC": "RabBitcoin",
    "SUSD": "sUSD",
    "VISTA": "Ethervista",
    "FAR": "Farcana",
    "COOK": "Cook Finance",
    "PYTHIA": "Pythia",
    "SEKOIA": "sekoia by Virtuals",
    "CAH": "Moon Tropica",
    "BZZ": "Swarm",
    "METAV": "METAVERSE",
    "SWAP": "TrustSwap",
    "SAMO": "Samoyedcoin",
    "TROY": "TROY",
    "IDRT": "Rupiah Token",
    "HEZ": "Hermez Network",
    "AA": "A3S Protocol",
    "KRL": "Kryll",
    "VLX": "Velas",
    "CKP": "Cakepie",
    "NEON": "Neon EVM",
    "HEGE": "Hege",
    "MONA": "MonaCoin",
    "DEGENAI": "Degen Spartan AI",
    "VAI": "VAIOT",
    "PSTAKE": "pSTAKE Finance",
    "OG": "OG Fan Token",
    "GTAI": "GT Protocol",
    "VINU": "Vita Inu",
    "BCUT": "bitsCrunch",
    "GLDGOV": "Gold DAO",
    "BIOT": "BioPassport Token",
    "DLC": "Diamond Launch",
    "CREAM": "Cream Finance",
    "USDV": "Verified USD",
    "BELLS": "Bellscoin",
    "GLQ": "Graphlinq Chain",
    "$MICRO": "Micro GPT",
    "WNCG": "Nine Chronicles",
    "10SET": "Tenset",
    "HGPT": "HyperGPT",
    "CELL": "Cellframe",
    "ULTI": "Ultiverse",
    "VOLT": "Volt Inu",
    "REEF": "Reef",
    "KOIN": "Koinos",
    "BAR": "FC Barcelona Fan Token",
    "MVC": "MileVerse",
    "HARD": "Kava Lend",
    "HAPPY": "Happy Cat",
    "BOTIFY": "BOTIFY"
}